version: '3.8'

services:
  psn-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8032:8032"
    restart: always
    container_name: psn-frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8032/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s 