services:
  psn-frontend:
    image: kevlargroup/psn-rwanda-frontend:latest
    ports:
      - "8032:8032"
    restart: always
    container_name: psn-frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8032/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - psn-network

networks:
  psn-network:
    name: psn-network
    driver: bridge 